CREATE TABLE chat_rooms (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '聊天室ID',
    name VARCHAR(100) NOT NULL COMMENT '聊天室名称',
    is_group BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否为群聊',
    creator_id BIGINT UNSIGNED NOT NULL COMMENT '创建者ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    FOREIGN KEY (creator_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='聊天室表';